[package]
name = "unbg-runtime-ort"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = ["directml", "cuda", "coreml"]
directml = ["ort/directml"]
cuda = ["ort/cuda"]
coreml = ["ort/coreml"]

[dependencies]
anyhow.workspace = true
image.workspace = true
ndarray.workspace = true
serde.workspace = true
serde_json.workspace = true
unbg-model-registry = { path = "../unbg-model-registry" }
unbg-core = { path = "../unbg-core" }

[target.'cfg(any(target_os = "android", target_os = "ios"))'.dependencies]
ort = { version = "2.0.0-rc.12", default-features = false, features = ["std", "ndarray", "download-binaries", "tls-rustls", "api-24"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
ort = { version = "2.0.0-rc.12", default-features = false, features = ["std", "ndarray", "download-binaries", "tls-rustls", "load-dynamic", "copy-dylibs", "api-24"] }
