name: security

on:
  pull_request:
  push:
    branches: [main]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dtolnay/rust-toolchain@4be7066ada62dd38de10e7b70166bc74ed198c30 # stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: Install cargo-audit
        run: cargo install cargo-audit --version 0.22.2 --locked
      - name: Run cargo audit
        run: cargo audit
      - name: Install cargo-cyclonedx
        run: cargo install cargo-cyclonedx --version 0.5.9 --locked
      - name: Generate SBOM
        run: cargo cyclonedx --format json --override-filename sbom.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: sbom
          path: "**/sbom.json"
